# Generated by Django 5.2.1 on 2025-08-19 07:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='myapp_notif_recipie_84382f_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_ct',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='extra',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
