# Generated by Django 5.2.1 on 2025-08-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_notification_myapp_notif_recipie_84382f_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notification',
            table='myapp_notification',
        ),
    ]
